### PR TITLE
Adds style, form alter for google sso/openid connect form

### PR DESCRIPTION
**Pull request by furyuri**
## Purpose:
- Styles the Google SSO Login button
- Updates button text.

### CODE REVIEW

**Comment by laura-johnson** [comment]
Four_Kitchens_Karaoke

Looks good to me! I get an error when I try to use the button to sign in, but I'm assuming that won't be the case when it's on a real domain:


Sign_in_-_Google_Accounts

**Comment by furyuri** [comment]
@laura-johnson - Thanks! 
Just to be sure, can you tell me which URL and environment you were on when you tested it? Was it locally? (Likely the key/secret were missing which is expected/fine.)

**Comment by laura-johnson** [comment]
Yes, locally! And yes I'm guessing the key/secret are missing (I didn't see any setup info for that).

**Review by laura-johnson — APPROVED** [review]
This looks good... it might be a good idea to add instructions to the README for adding the key/secret to enable sso for local, but that can be a separate ticket.

**Pull request merged**
